note/urls.py
from django.urls import path

from . import views

app_name = "note"

urlpatterns = [
    path("", views.index, name="index"),
    path("noteCreate", views.noteCreate, name="noteCreate"),
    path("signup", views.signup, name="signup"),
    path("login/", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
]

noter/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("note.urls")),
    # path("login", include("note.urls")),
    path("admin/", admin.site.urls),
]

note/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Note(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=30)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

note/views.py
from django.shortcuts import redirect, render
from .models import Note, User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login as login_process, logout as logout_process
# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required

# @login_required
def index(request):
    notes = Note.objects.all()
    context = {"Notes":notes}
    return render(request, 'index.html', context)
    # return HttpResponse("Hello, world. You're at the polls index.")

# @login_required
def noteCreate(request):
    if request.method == "POST":
        author = request.user
        title = request.POST.get("title")
        content = request.POST.get("content")
        createNote = Note.objects.create(author=author, title=title, content=content)
        createNote.save()
        return render(request, "noteCreate.html")
    else:
        notes = Note.objects.all()
        context = {"Notes": notes}
        return render(request, "noteCreate.html", context)

def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, "login.html")
        else:
            form = UserCreationForm()
            return render(request, "signup.html", {'form': form})
        
    else:
        form = UserCreationForm()
    return render(request, "signup.html", {'form': form})

def login(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("pwd")
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login_process(request, user)
            notes = Note.objects.all()
            context = {"Notes": notes}
            return render(request, "index.html", context)
        # else:
        #     return render(request, "login.html")
    else:
        return render(request, "login.html")

def logout_view(request):
    logout_process(request)
    return redirect('login')

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'note:index' %}">Ur Home</a>
        <a class="navbar-brand" href="{% url 'note:noteCreate' %}">Noter create</a>
        <!-- <a class="navbar-brand" href="jio">Page 1</a> -->
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <!-- <ul class="nav navbar-nav">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#">Page 1</a></li>
          <li><a href="#">Page 2</a></li>
          <li><a href="#">Page 3</a></li>
        </ul> -->
        <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'note:signup' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
          {% if user.is_authenticated %}
          <li><a href="{% url 'note:logout' %}"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
          {% else %}
          <li><a href="{% url 'note:login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

<body>

<div class="container h-100 d-flex justify-content-center align-items-center">
  <h1>My Notes</h1>
  <p><b>Your favourite note maker.</b></p>
{% for note in Notes %}
  <div class="row">
    <div class="col-md-6">
      <div class="card" style="width: 50rem;">
        <div class="card-body">
          <h5 class="card-title">{{note.title}} by {{note.author}}</h5>
          <h6 class="card-subtitle mb-2 text-body-secondary">{{note.created_at}}</h6>
          <p class="card-text">{{note.content}}</p>
        </div>
      </div>
    </div>
        
  </div>
  <hr>
{% endfor %}
</div>

</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>

<body>

<div class="container h-100 d-flex justify-content-center align-items-center">
    <h1>SignUp to Note Creater</h1>
    <p>Your note saver for the day</p>

  <div class="row">
    <div class="col-sm-12">
        <form method="POST" class="form-horizontal">
          {% csrf_token %}  
            <div class="form-group">
              <label class="control-label col-sm-2" for="username">Username:</label>
              <div class="col-sm-10">
                <input type="text" class="form-control" name="username" id="username" placeholder="Enter UserName">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-sm-2" for="pwd">Password:</label>
              <div class="col-sm-10">
                <input type="password" class="form-control" name="pwd" id="pwd" placeholder="Enter password">
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                <div class="checkbox">
                  <label><input type="checkbox"> Remember me</label>
                </div>
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" id="submit" class="btn btn-default">Submit</button>
              </div>
            </div>
          </form>
          <a href="{% url 'note:signup' %}" class="btn btn-default">Go SignUp</a>
    </div>
  </div>
</div>

</body>
</html>

templates/noteCreate.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'note:index' %}">Ur Home - Joshua</a>
        <a class="navbar-brand" href="{% url 'note:noteCreate' %}">Noter create</a>
        <!-- <a class="navbar-brand" href="jio">Page 1</a> -->
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <!-- <ul class="nav navbar-nav">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#">Page 1</a></li>
          <li><a href="#">Page 2</a></li>
          <li><a href="#">Page 3</a></li>
        </ul> -->
        <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'note:signup' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
          <li><a href="{% url 'note:logout' %}"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
        </ul>
      </div>
    </div>
  </nav>

<body>

<div class="container h-100 d-flex justify-content-center align-items-center">
  <h1>My First Bootstrap Page</h1>
  <p>This is some text.</p>

  <div class="row">
    
    <div class="col-md-6">
        <form method="POST" enctype="multipart/form-data" class="form-horizontal">
          {% csrf_token %}  
          <div class="form-group">
              <label class="control-label col-sm-2" for="title">Title:</label>
              <div class="col-sm-10">
                <input type="text" class="form-control" name="title" id="title" placeholder="Enter title">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-sm-2" for="pwd">Enter Note:</label>
              <div class="col-sm-10">
                <textarea class="form-control" name="content" id="content" rows="4" placeholder="Enter Note"></textarea>
                <!-- <label class="form-label" for="textAreaExample">Message</label> -->
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                <div class="checkbox">
                  <label><input type="checkbox"> Remember me</label>
                </div>
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" id="submit" class="btn btn-default">Submit</button>
              </div>
            </div>
          </form>
    </div>
  </div>
</div>

</body>
</html>

templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>

<body>

<div class="container h-100 d-flex justify-content-center align-items-center">
  <h1>SignUp to Note Creater</h1>
  <p>Your note saver for the day</p>

    <div class="container">

        <div class="card">
            <img src="..." class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title">Card title</h5>
              <form method="POST" class="form-horizontal">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="form-group">
                  <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-primary">Submit</button>
                  </div>
                </div>
              </form>
              <a href="{% url 'note:login' %}" class="btn btn-default">Go login</a>
            </div>
          </div>
        

    </div>
</div>

</body>
</html>